### PR TITLE
Improve logs and fix bugs

### PR DESCRIPTION
**Pull request by gregaubert**
It seems like it's not working sometimes when it should, I added some logs to better understand what's going on.

### CODE REVIEW

**Review by antonio-garcia-sonarsource — COMMENTED** [review]
Code looks good! Did you test locally that it works correctly when no tickets are found?

**Comment by gregaubert** [comment]
> Code looks good! Did you test locally that it works correctly when no tickets are found?

I didn't know we could test locally, how do you do that?

**Comment by antonio-garcia-sonarsource** [comment]
> > Code looks good! Did you test locally that it works correctly when no tickets are found?
> 
> I didn't know we could test locally, how do you do that?

Found it! https://xtranet-sonarsource.atlassian.net/wiki/spaces/HELPDESK/pages/1764130965/Testing+plan+for+SonarCloud+team#Jira-synchronisation

**Comment by gregaubert** [comment]
I still don't understand how to test it, seems like in the end I have to merge to master to test ?

**Comment by antonio-garcia-sonarsource** [comment]
> I still don't understand how to test it, seems like in the end I have to merge to master to test ?

Hmmmm I confused this with the code in Core. Indeed you need to merge it to test this part, then we can test with https://github.com/drautureau-sonarsource/test-jira-migration

**Review by antonio-garcia-sonarsource — APPROVED** [review]

**Comment by gregaubert** [comment]
@antonio-garcia-sonarsource actually I was able to test all the behaviors on this PR: https://github.com/SonarSource/sonarcloud-core/pull/4969

**Comment by antonio-garcia-sonarsource** [comment]
> @antonio-garcia-sonarsource actually I was able to test all the behaviors on this PR: [SonarSource/sonarcloud-core#4969](https://github.com/SonarSource/sonarcloud-core/pull/4969)
> 
> I fixed the bug that we had and updated to node 16 to get rid of the warning github was showing.

I see, nice!! It would be nice to add a small comment in the README so we remember how to test this action in the future.

**Pull request merged**
